cartridge-gg/cainome

crates/parser/src/tokens/composite.rs
crates/rs/src/expand/struct.rs

In namespaces of cairo types or structure fields, we may encounter some rust reserved keywords.
This PR is a first step to escape them, a more generic solution may be found to solve it more broadly.

fix: add support for more rust reserved keywords

---

crates/cairo-serde/src/types/array_legacy.rs
crates/cairo-serde/src/types/starknet.rs
crates/rs/src/expand/enum.rs
crates/rs/src/expand/struct.rs

Added PartialOrd when generating struct to allow comparison operations (<, >, <=, >=).

feat: add trait partial ord

---

crates/cairo-serde/src/types/array_legacy.rs

fix: ensure empty cairo0 array can be deserialized

---

contracts/.gitignore
contracts/Makefile
contracts/src/basic.cairo
contracts/src/lib.cairo
crates/cairo-serde/README.md
crates/cairo-serde/src/error.rs
crates/cairo-serde/src/lib.rs
crates/cairo-serde/src/types/integers.rs
crates/cairo-serde/src/types/mod.rs
crates/cairo-serde/src/types/non_zero.rs
crates/cairo-serde/src/types/starknet.rs
crates/cairo-serde/src/types/u256.rs
crates/parser/src/tokens/constants.rs
crates/rs-macro/src/spanned.rs
crates/rs/src/expand/types.rs
examples/simple_get_set.rs

The goal of this PR is twofold:
1. Add a missing `NonZero` type to the cainome repo. The type will be restricted to hold integers only.
2. Move the U256 type from generated code to the cainome repo directly. This would allow us to write methods such as `fn to_bytes_be(&self) -> [u8, 32];` on the type and allow it to be used with the new `NonZero` type.

Feature: Add corelib types

---

.github/workflows/lint.yml
Cargo.lock
crates/cairo-serde/Cargo.toml
crates/cairo-serde/src/lib.rs
crates/cairo-serde/src/types/array_legacy.rs
crates/cairo-serde/src/types/byte_array.rs
crates/cairo-serde/src/types/non_zero.rs
crates/cairo-serde/src/types/option.rs
crates/cairo-serde/src/types/result.rs
crates/cairo-serde/src/types/starknet.rs
crates/cairo-serde/src/types/u256.rs
crates/parser/src/abi/parser.rs
crates/parser/src/abi/parser_legacy.rs
crates/parser/src/tokens/composite.rs
crates/rs-macro/src/macro_inputs.rs
crates/rs-macro/src/macro_inputs_legacy.rs
crates/rs/src/expand/enum.rs
crates/rs/src/expand/function.rs
crates/rs/src/expand/struct.rs
crates/rs/src/expand/utils.rs
rust-toolchain.toml
scripts/docs.sh

A tag has been done to add some serde support on generated type.
This is a tmp solution, we should add a way for the user to define that. But as some types are built-in, we should also think about how the built-in types can follow this behavior.

feat: import serde 1

---

crates/rs-macro/src/lib.rs
crates/rs-macro/src/macro_inputs.rs
crates/rs/src/execution_version.rs
crates/rs/src/expand/function.rs
crates/rs/src/lib.rs
examples/exec_v3.rs
src/bin/cli/args.rs
src/bin/cli/main.rs
src/bin/cli/plugins/builtins/rust.rs
src/bin/cli/plugins/mod.rs

feat: add execution v1 or v3 as a parameter

---

crates/rs-macro/src/macro_inputs_legacy.rs
crates/rs/src/expand/function.rs
examples/cairo0_account.rs

Avoid writing scripts to extract the ABI adding support to parse `LegacyContractClass` when working with Cairo 0.

feat: support LegacyContractClass to load ABI from artifacts

---

Cargo.lock
Cargo.toml
crates/parser/src/abi/parser.rs

Ensures that any composite inner is resolved to parsed struct/enums when it applies.

fix: ensure composite inners are resolved to known types

---

contracts/Makefile
contracts/src/lib.cairo
crates/rs-macro/src/lib.rs
crates/rs-macro/src/macro_inputs.rs
crates/rs/src/expand/enum.rs
crates/rs/src/expand/struct.rs
crates/rs/src/lib.rs
examples/structs.rs
src/bin/cli/args.rs
src/bin/cli/main.rs
src/bin/cli/plugins/builtins/rust.rs
src/bin/cli/plugins/mod.rs

Now by default cainome doesn't add any derive to generated types. They must be passed by the user using `derives(Trait1, Trait2)`.
BREAKING CHANGE: breaking if downstream users rely on previously derived trait.

feat!: add custom derives from user

---

crates/rs-macro/src/macro_inputs.rs

Ensure aliases input are escaped to avoid not finding them when iterating on types.

fix: escape input strings for token alias

---

.github/workflows/ci.yml
Cargo.lock
crates/rs-macro/Cargo.toml
crates/rs-macro/src/lib.rs
crates/rs-macro/src/macro_inputs.rs
crates/rs-macro/src/macro_inputs_legacy.rs
crates/rs-macro/tests/abigen/duplicate_abi_type.rs
crates/rs-macro/tests/abigen/duplicate_abi_type.stderr
crates/rs-macro/tests/abigen/duplicate_alias_name.rs
crates/rs-macro/tests/abigen/duplicate_alias_name.stderr
crates/rs-macro/tests/abigen/unexpected_named_parameter.rs
crates/rs-macro/tests/abigen/unexpected_named_parameter.stderr
crates/rs-macro/tests/tests.rs

- Adds proc-macro-error to replace some panics for the `abigen` and `abigen_legacy` macros
- Adds `trybuild` for some failing paths testing of the `abigen!`.

feat: error handling

---

Cargo.lock
Cargo.toml
crates/cairo-serde-derive/Cargo.toml
crates/cairo-serde-derive/src/derive_enum.rs
crates/cairo-serde-derive/src/derive_struct.rs
crates/cairo-serde-derive/src/lib.rs
examples/cairo_serde_derive.rs
src/cairo_serde_derive.rs
src/lib.rs

This is PR has [another one](https://github.com/cartridge-gg/cainome/pull/60) stacked on top.

Cairo Serde Derive

---

Cargo.lock
Cargo.toml

Package version in Cargo.toml was still 0.2.3 which is quite confusing in build output:
```console
Compiling cainome v0.2.3 (https://github.com/cartridge-gg/cainome?tag=v0.4.0#0d29bb06)
```

update package version in Cargo

---

contracts/src/gen.cairo
crates/cairo-serde/src/lib.rs
crates/rs/src/expand/enum.rs
crates/rs/src/expand/struct.rs
crates/rs/src/expand/utils.rs
examples/cairo_serde_derive.rs
examples/structs.rs

Most of interop required by Cainome data are JavaScript clients.
JavaScript uses the IEEE 754 standard for floating-point arithmetic, which can safely represent integers up to 2^53 - 1.
Hence, any integer greater than `u32` are serialized using `lower hex` format.
Current support if for single value and tuple. In a tuple, if one value is subject to be serialized with `hex`, all the values are actually required to support lower hex format.
This might be a limitation in some situations though.

feat: serialize integers higher than u32 in hex format

---

crates/parser/src/abi/parser.rs
crates/parser/src/tokens/mod.rs
crates/parser/test_data/dojo_starter-directions_available.abi.json
crates/parser/test_data/struct_tuple.abi.json

For dojo.js bindgen we need to add copies of composites inside nested `core::array::Array` fields.
We might need to do the same for `tuple` but I need to test with real abi so PR will be completed tomorrow

feat: copy inner composite for struct array keys

---

contracts/src/gen.cairo
crates/rs/src/expand/event.rs
crates/rs/src/expand/struct.rs
crates/rs/src/expand/utils.rs
examples/structs.rs

Add two functions to event structs:
```rust
fn event_selector() -> Felt;
fn event_name() -> &str;
```

feat: add event selector for event structs

---

crates/rs-macro/src/macro_inputs.rs
examples/json_abi.rs

Allow embedding the ABI JSON array directly into the macro call as one of the way of passing the ABI. There's no breaking changes because the old behaviours are still preserved.
Usage example:
```rust
abigen!(MyContract, [
{
"type": "function",
"name": "foo",
"inputs": [],
"outputs": [
{
"type": "core::bool"
}
],
"state_mutability": "view"
}]);
```

feat(macro): support embedding abi as literal json

---

crates/rs/src/expand/utils.rs
examples/rust_keyword.rs

Currently, `abigen!` doesn't handle the case where an ABI name is a one of Rust [keywords](https://doc.rust-lang.org/1.65.0/reference/keywords.html). 
For example:
```
abigen!(Example, [
{
"type": "function",
"name": "move",
"inputs": [
{
"name": "direction",
"type": "dojo_examples::models::Direction"
}
],
"outputs": [],
"state_mutability": "external"
},
..
]);
// will generate this
#[allow(clippy::ptr_arg)]
#[allow(clippy::too_many_arguments)]
pub fn move(&self,direction: &Direction) -> starknet::accounts::ExecutionV1<A>{
..
}
```
Rust will complain:
```console
error: expected identifier, found keyword `move`
```
This PR will append `r#` to names that are considered as Rust keywords.

feat: handle raw ident

---

crates/parser/src/tokens/mod.rs

During hydrate of the tokens, the `type_path` (including generics) was used. This was causing issues during the lookup of composite tokens.
This PR aims at providing a better lookup by discarding the generic part of the path, and focusing on the composite type.

fix: use type path without generic during hydrate of tokens

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/release.yml

https://github.com/actions-rs/toolchain is deprecated so I'm updating to widespead alternative

chore: change ci actions-rs to dtolnay, version bumps

---

bin/lint
src/bin/cli/contract/mod.rs

Allow explicit definition of contract files to include from artifacts path to provide more control over which contracts are parsed.

Update parser config for contract file inclusion
